backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "secciones"
    label: "Secciones"
    folder: "content/secciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }

  - name: "publicaciones"
    label: "Publicaciones"
    folder: "content/publicaciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Contenido", name: "contenido", widget: "markdown" }
      - { label: "Sección", name: "seccionId", widget: "relation", collection: "secciones", search_fields: ["nombre"], value_field: "nombre", display_fields: ["nombre"] }
