backend:
  name: git-gateway
  branch: main   # usa "main" porque tu repo está en esa rama

media_folder: "uploads"   # carpeta donde se guardan imágenes (no usarás Storage de pago)
public_folder: "/uploads"

collections:
  - name: "secciones"
    label: "Secciones"
    folder: "content/secciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "description", label: "Descripción", widget: "text" }
      - { name: "body", label: "Contenido", widget: "markdown" }

  - name: "publicaciones"
    label: "Publicaciones"
    folder: "content/publicaciones"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "date", label: "Fecha", widget: "datetime" }
      - { name: "body", label: "Contenido", widget: "markdown" }
      - { name: "enlace", label: "Enlace (YouTube, Imgur, etc.)", widget: "string", required: false }
